import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { AppProviders } from './providers';

const plusJakartaSans = Roboto({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'next chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className}`}>
        <AppProviders>{children}</AppProviders>
      </body>
    </html>
  );
}
