import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import CustomQueryClientProvider from './lib/providers/CustomQueryProvider';
import Layout from './ui/Layout/Layout';
import './globals.css';

const plusJakartaSans = Roboto({
  subsets: ['latin', 'cyrillic'],
});

export const metadata: Metadata = {
  title: 'next chat',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${plusJakartaSans.className}`}>
        <CustomQueryClientProvider>
          <Layout>{children}</Layout>
        </CustomQueryClientProvider>
      </body>
    </html>
  );
}
